myApp:
  name: Kunal Kumar Jha
  description: |
    kunal jha is my name
    this is a multiline string
    and heck ya this is human readable
  key: wow great
  array:
    - key1: value1
      randomKey: valueRandom
    - key2: value2
      randomKey2: valueRandom2
